theme: jekyll-theme-hacker
title: Scripts for Proxmox
description: I created this collection of scripts to make setting up Proxmox servers easier and also faster for me.
markdown: kramdown
kramdown:
  parse_block_html: true
